@id=19ee26b0-4fa3-42b3-8fa6-d3c8fe544d6e
PUT http://localhost:5234/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 4",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}